[terminal]
shell = "/bin/bash"

[general]
import = [
  "~/.config/alacritty/themes/themes/ayu_light.toml"
]

[window]
padding = { x = 12, y = 12 }

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 12
normal = { family = "Monego", style = "Regular" }
bold = { family = "Monego", style = "Regular" }

[keyboard]
bindings = [
  { key = "Equals", mods = "Control", action = "None" },
  { key = "Plus", mods = "Control", action = "None" },
  { key = "Minus", mods = "Control", action = "None" },
  { key = "NumpadAdd", mods = "Control", action = "None" },
  { key = "NumpadSubtract", mods = "Control", action = "None" }
]
